# Generated by Django 2.2.16 on 2022-09-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('shortname', models.CharField(max_length=50, verbose_name='Краткое название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/dishes/', verbose_name='Фото')),
                ('filename', models.CharField(blank=True, max_length=300, null=True, verbose_name='Путь к файлу')),
                ('image_id', models.CharField(blank=True, max_length=300, null=True, verbose_name='ID фото в TG')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('date_of_menu', models.DateField(blank=True, verbose_name='Дата меню')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('dishes', models.ManyToManyField(to='db.Dishes', verbose_name='Блюда')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['date_of_menu'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('input_firstname', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя')),
                ('input_lastname', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия')),
                ('input_phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя Tg')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия Tg')),
                ('is_register', models.BooleanField(default=False, verbose_name='Зарегистрирован ли')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_blocked_bot', models.BooleanField(default=False, verbose_name='Заблокирвал бота')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Права админа')),
                ('is_allow_mail', models.BooleanField(default=False, verbose_name='Разрешена ли рассылка')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_servings', models.PositiveIntegerField(verbose_name='Количество порций')),
                ('payment_type', models.CharField(max_length=30, verbose_name='Тип оплаты')),
                ('cash_change', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сдача с')),
                ('delivery', models.CharField(max_length=30, verbose_name='Тип получения')),
                ('delivery_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес получения')),
                ('comment', models.CharField(blank=True, max_length=400, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='db.Menu', verbose_name='Меню')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='db.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
